%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Copyright 2014 the National Renewable Energy Laboratory and Sandia Corporation
% 
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
% 
%     http://www.apache.org/licenses/LICENSE-2.0
% 
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

classdef ptoSimClass<handle
    properties
        name = 'NOT DEFINED'
        piston  =   struct('topA'         ,0.0378,...
                           'botA'         ,0.0378,...
                           'Ap'           ,0.0378,...
                           'Vo'           ,0.5670,...
                           'Beta_e'       ,1.86e9,...
                           'pAi'          ,2.1333e+07,...
                           'pBi'          ,2.1333e+07)
                     
        valve   =   struct('Cd'           ,0.61,...
                           'Amax'         ,0.002,...
                           'Amin'         ,1e-8,...
                           'pMax'         ,1.5e6,...
                           'pMin'         ,0,...
                           'rho'          ,850,...
                           'k1'           ,1,...
                           'k2'           ,8.1374e-06)
                       
        highAccum = struct('VI0'          ,8,...
                           'del_p_r'      ,15e6,...
                           'pIrated'      ,31e6,...
                           'pIeq'         ,2.1333e+07,...
                           'pIlower_limit',2.1333e+07,...
                           'pIupper_limit',3.2000e+07,...
                           'pIprecharge'  ,1.9200e+07,...
                           'VIeq'         ,0.5800,...
                           'VImax'        ,2.4457,...
                           'VImin'        ,0.5800)
                       
        lowAccum  = struct('VI0'          ,6,...
                           'pIrated'      ,16e6,...
                           'pIupper_limit',2.1333e+07,...
                           'pIlower_limit',1.0667e+07,...
                           'pIprecharge'  ,9600000,...
                           'pIeq'         ,2.1333e+07,...
                           'VImax'        ,2.6081,...
                           'VImin'        ,0.4350,...
                           'VIeq'         ,2.6081)
                       
        motor    =  struct('angVelInit'   ,0,...
                           'alpha'        ,1,...
                           'D'            ,1.28e-4,...
                           'J'            ,20,...
                           'bg'           ,8,...
                           'bf'           ,0.4)
                       
        gen      =  struct('TgenBase'     ,2000,...
                           'omegaBase'    ,251.3,...
                           'driveEff'     ,0.98)
        machine  =  struct('Rs'           ,4.58,...
                           'Bfric'        ,-100,...
                           'tau_p'        ,0.072,...
                           'lambda_fd'    ,8,...
                           'Ls'           ,0.285,...
                           'theta_d_0'    ,0,...
                           'lambda_sq_0'  ,0,...
                           'lambda_sd_0'  ,8)
         ddload   = struct('Rload'        ,-117.6471) 
                         
    end
    
    methods
        function obj        = ptoSimClass(name)
                 obj.name   = name;
        end
    end
 
end

