%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Copyright 2014 the National Renewable Energy Laboratory and Sandia Corporation
% 
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
% 
%     http://www.apache.org/licenses/LICENSE-2.0
% 
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

classdef ptoSimClass<handle
    properties
        
        name = 'NOT DEFINED'
        
        piston  =   struct('topA'         ,'NOT DEFINED',...
                           'botA'         ,'NOT DEFINED',...
                           'Ap'           ,'NOT DEFINED',...
                           'Vo'           ,'NOT DEFINED',...
                           'Beta_e'       ,'NOT DEFINED',...
                           'pAi'          ,'NOT DEFINED',...
                           'pBi'          ,'NOT DEFINED')
                     
        valve   =   struct('Cd'           ,'NOT DEFINED',...
                           'Amax'         ,'NOT DEFINED',...
                           'Amin'         ,'NOT DEFINED',...
                           'pMax'         ,'NOT DEFINED',...
                           'pMin'         ,'NOT DEFINED',...
                           'rho'          ,'NOT DEFINED',...
                           'k1'           ,'NOT DEFINED',...
                           'k2'           ,'NOT DEFINED')
                       
        accum  =    struct('VI0'          ,'NOT DEFINED',...
                           'pIrated'      ,'NOT DEFINED',...
                           'pIupper_limit','NOT DEFINED',...
                           'pIlower_limit','NOT DEFINED',...
                           'pIprecharge'  ,'NOT DEFINED',...
                           'VImax'        ,'NOT DEFINED',...
                           'VImin'        ,'NOT DEFINED',...
                           'VIeq'         ,'NOT DEFINED',...
                           'pIeq'         ,'NOT DEFINED')
                                                              
        motor    =  struct('angVelInit'   ,'NOT DEFINED',...
                           'alpha'        ,'NOT DEFINED',...
                           'D'            ,'NOT DEFINED',...
                           'J'            ,'NOT DEFINED',...
                           'bg'           ,'NOT DEFINED',...
                           'bf'           ,'NOT DEFINED')
                       
        gen      =  struct('TgenBase'     ,'NOT DEFINED',...
                           'omegaBase'    ,'NOT DEFINED',...
                           'driveEff'     ,'NOT DEFINED')
                       
        directdrive=struct('Rs'           ,'NOT DEFINED',...
                           'Bfric'        ,'NOT DEFINED',...
                           'tau_p'        ,'NOT DEFINED',...
                           'lambda_fd'    ,'NOT DEFINED',...
                           'Ls'           ,'NOT DEFINED',...
                           'theta_d_0'    ,'NOT DEFINED',...
                           'lambda_sq_0'  ,'NOT DEFINED',...
                           'lambda_sd_0'  ,'NOT DEFINED',...
                           'Rload'        ,'NOT DEFINED')
                                
         dioderec = struct('n'            ,'NOT DEFINED',...
                           'VT'           ,'NOT DEFINED',...
                           'Is'           ,'NOT DEFINED',...
                           'C'            ,'NOT DEFINED',...
                           'V1_init'      ,'NOT DEFINED',...
                           'V2_init'      ,'NOT DEFINED',...
                           'R'            ,'NOT DEFINED')
                       
         telemech = struct('radius'       ,'NOT DEFINED',...
                           'offsetZ'      ,'NOT DEFINED',...
                           'hydArmInit'   ,'NOT DEFINED')
                           
                           
                         
    end
    
    
    methods
        function obj        = ptoSimClass(name)
                 obj.name   = name;
        end        
    end 
end

